[build]
  base    = "frontend"
  command = "gatsby build"
  publish = "frontend/public"

[context.production]
  environment = { GATSBY_AWS_COGNITO_USER_POOL_ID = "eu-central-1_FvQw3QTFr", GATSBY_AWS_COGNITO_CLIENT_ID = "2vhfrlr4ul40v6haf9ov9ov5oi", GATSBY_GOOGLE_ANALYTICS_ID = "Iamnotvalid" }